version: '3'
services:
  nginx:
    build:
      context: . 
      dockerfile: ./frontend/Dockerfile
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"

  chatty: 
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      - PORT=3000

  mongo:
    image: mongo
    restart: always 
    environment:
      MONGO_INITDB_ROOT_USERNAME: etiane
      MONGO_INITDB_ROOT_PASSWORD: etiane
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: